hoster_name: "aeza" # название опрашиваемого хостера
number_ip_poll: 5 # количество IP адресов взятых из одной подсети
number_pings_to_one_ip: 5 # количество пингов к одному IP
max_ping: 60 # максимальный приемлемый пинг до сервера
debug: 1 # включить отображение логирующих сообщений
