hoster_name: "justhost" # название опрашиваемого хостера
number_randomly_prefixes_by_country: 5 # количество подсетей анализируемых в рамках одной страны
number_randomly_taken_ip_from_netblock: 5 # количество IP адресов взятых из одной подсети
number_pings_to_one_ip: 5 # количество пингов к одному IP
max_avg_ping: 60 # максимальный приемлемый пинг до сервера
max_hops: 16 # максимальное количество "прыжков" до сервера (traceroute будет сделан только при условии что средний ping до сервера будет ниже чем указанный в параметре max_avg_ping)
debug: 1 # включить отображение логирующих сообщений
try_update_asn_file: 1 # попытаться загрузить новый файл ASN файл
skip_country_code: ["RU", "GB", "AT", "US", "SC", "SG", "CN", "AE", "TR", "UA"] # список двухбуквенных обозначений стран, которые не будут анализироваться
